# Generated by Django 2.2.12 on 2020-04-01 14:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frontpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlatitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('currentlongtitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('currentAddress', models.TextField()),
                ('targetlatituide', models.DecimalField(decimal_places=27, max_digits=30)),
                ('targetlongtitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('targetAddress', models.TextField()),
                ('distance', models.IntegerField()),
                ('RouteCoordinate', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
